# HEDIS GSD Prediction Engine - Development Configuration

# Development Environment Overrides
# This file extends config.yaml with development-specific settings

# Data Configuration (Development)
data:
  raw_data_path: "data/raw"
  processed_data_path: "data/processed"
  measurement_year: 2008
  sample_size: 1000  # Use smaller sample for development

# Model Configuration (Development)
model:
  target_variable: "poor_glycemic_control"
  age_range:
    min: 18
    max: 75

# Training Configuration (Development)
training:
  test_size: 0.2
  random_state: 42
  cv_folds: 3  # Fewer folds for faster development
  models:
    logistic_regression:
      C: 1.0
      max_iter: 100  # Fewer iterations for faster training
      random_state: 42
    random_forest:
      n_estimators: 50  # Fewer trees for faster training
      max_depth: 5
      random_state: 42
      n_jobs: 2  # Limit parallel processing

# Feature Engineering Configuration (Development)
features:
  demographic_features: true
  comorbidity_features: true
  utilization_features: true
  diabetes_specific_features: true

# Evaluation Configuration (Development)
evaluation:
  threshold: 0.5
  demographic_groups:
    - "age_group"
    - "sex"
  clinical_thresholds:
    high_risk: 0.7
    medium_risk: 0.3
    low_risk: 0.1
  bias_metrics:
    - "demographic_parity"

# Prediction Configuration (Development)
prediction:
  default_model: "logistic_regression"
  model_path: "models_dev"
  risk_thresholds:
    high: 0.7
    medium: 0.3
    low: 0.1

# Logging Configuration (Development)
logging:
  level: "DEBUG"  # More verbose logging for development
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_logging: true
  log_file: "logs/dev.log"

# Security Configuration (Development)
security:
  phi_logging: false  # Never log PHI
  audit_logging: true
  hash_identifiers: true
  debug_mode: true  # Enable debug features

# Performance Configuration (Development)
performance:
  batch_size: 100  # Smaller batches for development
  max_memory_usage: "1GB"
  parallel_processing: false  # Disable for easier debugging

# Development-Specific Settings
development:
  enable_profiling: true
  enable_debugging: true
  mock_data: false
  fast_training: true
  verbose_output: true
