# HEDIS Star Rating Portfolio Optimizer - Configuration
# Version: 2.0.0
# Last Updated: 2025-10-23

# ============================================================================
# PROJECT METADATA
# ============================================================================
project:
  name: "HEDIS Star Rating Portfolio Optimizer"
  version: "2.0.0"
  measurement_year: 2025
  description: "Enterprise-grade AI platform for optimizing HEDIS Star Rating performance across 12 quality measures"
  
  # Portfolio value estimates
  portfolio_value:
    tier1_diabetes: "$720K-$1.23M"
    tier2_cardiovascular: "$650K-$1M"
    tier3_cancer_screening: "$300-450K"
    tier4_health_equity: "$20-40M (at risk)"
    total: "$22-42M"

# ============================================================================
# MEASURE REGISTRY - 12 HEDIS Measures
# ============================================================================
measures:
  # ----- TIER 1: Diabetes Core (5 measures) -----
  GSD:
    name: "Glycemic Status Assessment for Patients with Diabetes"
    code: "GSD"
    tier: 1
    weight: 3  # Triple-weighted
    status: "production"  # Currently operational
    target_population: "diabetes_18_75"
    data_sources: ["claims", "labs"]
    hedis_spec: "MY2025 Volume 2"
    star_value: "$360-615K"
    model:
      auc_target: 0.90
      current_auc: 0.91
    features:
      count: 25
      types: ["demographics", "comorbidities", "utilization", "labs"]
  
  KED:
    name: "Kidney Health Evaluation for Patients with Diabetes"
    code: "KED"
    tier: 1
    weight: 3  # Triple-weighted
    status: "development"  # NEW 2025
    new_measure: true
    target_population: "diabetes_18_75"
    data_sources: ["claims", "labs"]
    hedis_spec: "MY2025 Volume 2 (NEW)"
    star_value: "$360-615K"
    model:
      auc_target: 0.85
    features:
      required: ["eGFR", "ACR", "ACE_ARB_meds", "nephrology_visits"]
  
  EED:
    name: "Eye Exam for Patients with Diabetes"
    code: "EED"
    tier: 1
    weight: 1
    status: "development"
    target_population: "diabetes_18_75"
    data_sources: ["claims"]
    hedis_spec: "MY2025 Volume 2"
    star_value: "$120-205K"
    model:
      auc_target: 0.85
    features:
      required: ["retinal_exam_history", "retinopathy_dx", "exam_frequency"]
  
  PDC_DR:
    name: "Medication Adherence for Diabetes Medications"
    code: "PDC-DR"
    tier: 1
    weight: 1
    status: "development"
    target_population: "diabetes_18_75_on_meds"
    data_sources: ["pharmacy"]
    hedis_spec: "MY2025 Volume 2"
    star_value: "$120-205K"
    pdc_threshold: 0.80  # 80% adherence
    model:
      auc_target: 0.85
    features:
      required: ["days_supply", "fill_dates", "therapy_gaps", "med_switches"]
  
  BPD:
    name: "Blood Pressure Control for Patients with Diabetes"
    code: "BPD"
    tier: 1
    weight: 1
    status: "development"  # NEW 2025
    new_measure: true
    target_population: "diabetes_18_75"
    data_sources: ["claims", "vitals"]
    hedis_spec: "MY2025 Volume 2 (NEW)"
    star_value: "$120-205K"
    bp_target: "140/90"  # <140 systolic AND <90 diastolic
    model:
      auc_target: 0.85
    features:
      required: ["bp_readings", "htn_dx", "htn_meds"]
  
  # ----- TIER 2: Cardiovascular Comorbidity (4 measures) -----
  CBP:
    name: "Controlling High Blood Pressure"
    code: "CBP"
    tier: 2
    weight: 3  # Triple-weighted
    status: "planned"
    target_population: "hypertension_18_85"
    data_sources: ["claims", "vitals"]
    hedis_spec: "MY2025 Volume 2"
    star_value: "$360-615K"
    bp_target: "140/90"
    model:
      auc_target: 0.85
  
  SUPD:
    name: "Statin Therapy for Patients with Diabetes"
    code: "SUPD"
    tier: 2
    weight: 1
    status: "planned"
    target_population: "diabetes_40_75_with_cvd_risk"
    data_sources: ["claims", "pharmacy"]
    hedis_spec: "MY2025 Volume 2"
    star_value: "$120-205K"
    model:
      auc_target: 0.85
  
  PDC_RASA:
    name: "Medication Adherence for Hypertension (RAS antagonists)"
    code: "PDC-RASA"
    tier: 2
    weight: 1
    status: "planned"
    target_population: "hypertension_18_85_on_rasa"
    data_sources: ["pharmacy"]
    hedis_spec: "MY2025 Volume 2"
    star_value: "$120-205K"
    pdc_threshold: 0.80
    model:
      auc_target: 0.85
  
  PDC_STA:
    name: "Medication Adherence for Cholesterol (Statins)"
    code: "PDC-STA"
    tier: 2
    weight: 1
    status: "planned"
    target_population: "hyperlipidemia_18_85_on_statins"
    data_sources: ["pharmacy"]
    hedis_spec: "MY2025 Volume 2"
    star_value: "$120-205K"
    pdc_threshold: 0.80
    model:
      auc_target: 0.85
  
  # ----- TIER 3: Cancer Screening (2 measures) -----
  BCS:
    name: "Breast Cancer Screening"
    code: "BCS"
    tier: 3
    weight: 1
    status: "planned"
    target_population: "women_50_74"
    data_sources: ["claims"]
    hedis_spec: "MY2025 Volume 2"
    star_value: "$150-225K"
    screening_interval: "24 months"
    model:
      auc_target: 0.85
  
  COL:
    name: "Colorectal Cancer Screening"
    code: "COL"
    tier: 3
    weight: 1
    status: "planned"
    target_population: "adults_50_75"
    data_sources: ["claims"]
    hedis_spec: "MY2025 Volume 2"
    star_value: "$150-225K"
    screening_methods: ["colonoscopy", "FIT", "cologuard", "sigmoidoscopy"]
    model:
      auc_target: 0.85
  
  # ----- TIER 4: Health Equity Index (1 measure) -----
  HEI:
    name: "Health Equity Index Reward Factor"
    code: "HEI"
    tier: 4
    weight: "5%"  # 5% bonus or penalty
    status: "planned"
    critical: true  # Mandatory by 2027
    target_population: "all_members"
    data_sources: ["all_measures", "sdoh"]
    hedis_spec: "MY2027 (starts MY2025)"
    star_value: "$20-40M (at risk)"
    bonus_max: 5  # percentage points
    penalty_max: -5  # percentage points
    underserved_populations:
      - "dual_eligible"
      - "low_income_subsidy"
      - "disability"
      - "minority_race_ethnicity"
    model:
      type: "disparity_analysis"
      metrics: ["measure_gap", "improvement_rate"]

# ============================================================================
# DATA CONFIGURATION
# ============================================================================
data:
  # Data sources
  raw_data_path: "data/raw"
  processed_data_path: "data/processed"
  synthetic_data_path: "data/synthetic"
  
  # Measurement year configuration
  measurement_year: 2025
  index_date: "2025-12-31"  # December 31 of measurement year
  
  # Data source types
  sources:
    claims:
      types: ["inpatient", "outpatient", "carrier", "professional"]
      format: "csv"
      encoding: "utf-8"
    
    pharmacy:
      types: ["prescription_fills"]
      ndc_required: true
      format: "csv"
    
    labs:
      types: ["HbA1c", "eGFR", "ACR", "lipids"]
      format: "csv"
    
    vitals:
      types: ["blood_pressure", "weight", "bmi"]
      format: "csv"
    
    screenings:
      types: ["mammography", "colonoscopy", "retinal_exam"]
      format: "csv"
    
    sdoh:
      types: ["dual_eligible", "lis", "disability", "race_ethnicity"]
      format: "csv"
      hipaa_compliant: true

  # Synthetic data generation
  synthetic:
    enabled: true
    seed: 42
    sample_size: 50000
    match_hedis_specs: true

# ============================================================================
# STAR RATING CONFIGURATION
# ============================================================================
star_rating:
  # Triple-weighted measures (3x impact)
  triple_weighted_measures:
    - "GSD"
    - "KED"
    - "CBP"
  
  # Star rating calculation
  total_possible_points: 100
  star_thresholds:
    5_stars: 90
    4_5_stars: 85
    4_stars: 75
    3_5_stars: 65
    3_stars: 50
    2_5_stars: 40
    2_stars: 25
    1_5_stars: 15
    1_star: 0
  
  # Financial impact per Star level
  revenue_per_star_point: 50000  # $50K per 0.1 Star point
  revenue_per_full_star: 500000  # $500K per full Star
  
  # Health Equity Index
  hei:
    enabled: true
    mandatory_year: 2027
    bonus_max: 5  # 5% bonus
    penalty_max: -5  # 5% penalty
    disparity_threshold: 0.05  # 5% gap triggers intervention
    
# ============================================================================
# MODEL CONFIGURATION
# ============================================================================
model:
  # Training configuration
  training:
    test_size: 0.2
    validation_size: 0.2
    cv_folds: 5
    random_state: 42
    stratify: true
    
    # Temporal validation (prevent data leakage)
    temporal_split:
      enabled: true
      train_years: [2023, 2024]
      test_year: 2025
  
  # Model types by measure
  algorithms:
    classification:
      - "logistic_regression"
      - "random_forest"
      - "xgboost"
      - "lightgbm"
    
    ensemble:
      enabled: true
      method: "stacking"
  
  # Hyperparameter tuning
  hyperparameter_tuning:
    enabled: true
    method: "randomized_search"
    n_iter: 50
    scoring: "roc_auc"
  
  # Feature engineering
  features:
    engineering_methods:
      - "one_hot_encoding"
      - "standard_scaling"
      - "polynomial_features"
      - "interaction_terms"
    
    selection:
      enabled: true
      method: "mutual_info"
      k_best: 30
  
  # Model evaluation
  evaluation:
    primary_metric: "roc_auc"
    secondary_metrics:
      - "precision"
      - "recall"
      - "f1_score"
      - "specificity"
      - "ppv"
      - "npv"
    
    # Healthcare-specific metrics
    healthcare_metrics:
      - "sensitivity"
      - "specificity"
      - "positive_likelihood_ratio"
      - "negative_likelihood_ratio"
    
    # Bias detection
    bias_analysis:
      enabled: true
      protected_groups:
        - "age_group"
        - "sex"
        - "race_ethnicity"
      fairness_threshold: 0.10  # 10% max disparity

# ============================================================================
# ROI CONFIGURATION
# ============================================================================
roi:
  # Star revenue calculations
  star_revenue_per_point: 50000  # $50K per 0.1 Star point
  
  # Intervention costs
  intervention_costs:
    phone_outreach: 25
    mail_outreach: 5
    home_visit: 150
    care_coordination: 300
    average: 150
  
  # ROI targets
  target_roi: 3.0  # 3:1 ROI minimum
  min_roi_for_intervention: 2.0
  
  # Gap closure assumptions
  gap_closure:
    optimistic: 0.20  # 20% gap closure
    realistic: 0.15   # 15% gap closure
    conservative: 0.10  # 10% gap closure

# ============================================================================
# PORTFOLIO OPTIMIZATION
# ============================================================================
portfolio:
  # Multi-measure optimization
  optimization:
    objective: "maximize_star_revenue"
    constraints:
      max_intervention_budget: 5000000  # $5M
      min_members_per_intervention: 100
    
    # Prioritization strategy
    prioritization:
      method: "roi_weighted"
      factors:
        - name: "star_impact"
          weight: 0.4
        - name: "measure_weight"
          weight: 0.3  # Triple-weighted = higher priority
        - name: "intervention_roi"
          weight: 0.2
        - name: "gap_closure_potential"
          weight: 0.1
  
  # Cross-measure analysis
  cross_measure:
    enabled: true
    shared_populations:
      - ["GSD", "KED", "EED", "PDC_DR", "BPD"]  # Diabetes portfolio
      - ["CBP", "PDC_RASA"]  # Hypertension portfolio
      - ["SUPD", "PDC_STA"]  # Cardiovascular portfolio

# ============================================================================
# SECURITY & COMPLIANCE
# ============================================================================
security:
  # HIPAA compliance
  phi_logging: false
  audit_logging: true
  hash_identifiers: true
  hash_algorithm: "sha256"
  
  # Data encryption
  encryption:
    at_rest: true
    in_transit: true
  
  # Access controls
  access_control:
    role_based: true
    audit_trail: true

# ============================================================================
# LOGGING & MONITORING
# ============================================================================
logging:
  level: "INFO"
  format: "json"
  destination: "file"
  file_path: "logs/portfolio_optimizer.log"
  rotation: "daily"
  retention_days: 90
  
  # PHI-safe logging
  phi_safe: true
  log_aggregates_only: true

# ============================================================================
# API CONFIGURATION (Phase 6)
# ============================================================================
api:
  enabled: false  # Will enable in Phase 6
  host: "0.0.0.0"
  port: 8000
  workers: 4
  timeout: 300
  
  # Endpoints
  endpoints:
    predict_single: "/api/v1/predict"
    predict_batch: "/api/v1/predict/batch"
    portfolio_optimize: "/api/v1/portfolio/optimize"
    measure_info: "/api/v1/measures/{measure_code}"
    health_check: "/health"

# ============================================================================
# TESTING CONFIGURATION
# ============================================================================
testing:
  coverage_threshold: 90  # 90% minimum coverage
  run_bias_tests: true
  run_hipaa_scans: true
  run_performance_tests: true
  
  # Test data
  test_data:
    use_synthetic: true
    sample_size: 1000
    seed: 123

# ============================================================================
# DEPLOYMENT CONFIGURATION
# ============================================================================
deployment:
  environment: "development"  # development, staging, production
  
  environments:
    development:
      debug: true
      synthetic_data: true
    
    staging:
      debug: false
      synthetic_data: true
    
    production:
      debug: false
      synthetic_data: false
      require_approval: true
